//! Boolean logic programs (15): ex070-ex084.

use super::{bool_case, bool_to_i64_case, Category, ProgramSpec, WitnessCase, WitnessValue};

pub fn programs() -> Vec<ProgramSpec> {
    vec![
        // ex070: and (a AND b)
        ProgramSpec {
            id: "ex070_and",
            intent: "Logical AND of two booleans",
            assembly_template: concat!(
                "FUNC 2 7\n",
                "PARAM BOOL\n",
                "PARAM BOOL\n",
                "REF 1\n",
                "REF 0\n",
                "AND\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST BOOL 0x0001 0x0000\n",
                "CONST BOOL 0x0001 0x0000\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                bool_case(&[true, true], true),
                bool_case(&[true, false], false),
                bool_case(&[false, true], false),
                bool_case(&[false, false], false),
            ],
            category: Category::BooleanLogic,
        },
        // ex071: or (a OR b)
        ProgramSpec {
            id: "ex071_or",
            intent: "Logical OR of two booleans",
            assembly_template: concat!(
                "FUNC 2 7\n",
                "PARAM BOOL\n",
                "PARAM BOOL\n",
                "REF 1\n",
                "REF 0\n",
                "OR\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST BOOL 0x0001 0x0000\n",
                "CONST BOOL 0x0000 0x0000\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                bool_case(&[true, false], true),
                bool_case(&[false, true], true),
                bool_case(&[true, true], true),
                bool_case(&[false, false], false),
            ],
            category: Category::BooleanLogic,
        },
        // ex072: not (NOT a)
        ProgramSpec {
            id: "ex072_not",
            intent: "Logical NOT of a boolean",
            assembly_template: concat!(
                "FUNC 1 5\n",
                "PARAM BOOL\n",
                "REF 0\n",
                "NOT\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST BOOL 0x0001 0x0000\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![bool_case(&[true], false), bool_case(&[false], true)],
            category: Category::BooleanLogic,
        },
        // ex073: xor (a XOR b)
        ProgramSpec {
            id: "ex073_xor",
            intent: "Logical XOR of two booleans",
            assembly_template: concat!(
                "FUNC 2 7\n",
                "PARAM BOOL\n",
                "PARAM BOOL\n",
                "REF 1\n",
                "REF 0\n",
                "XOR\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST BOOL 0x0001 0x0000\n",
                "CONST BOOL 0x0000 0x0000\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                bool_case(&[true, false], true),
                bool_case(&[false, true], true),
                bool_case(&[true, true], false),
                bool_case(&[false, false], false),
            ],
            category: Category::BooleanLogic,
        },
        // ex074: nand (NOT (a AND b))
        ProgramSpec {
            id: "ex074_nand",
            intent: "Logical NAND of two booleans",
            assembly_template: concat!(
                "FUNC 2 8\n",
                "PARAM BOOL\n",
                "PARAM BOOL\n",
                "REF 1\n",
                "REF 0\n",
                "AND\n",
                "NOT\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST BOOL 0x0001 0x0000\n",
                "CONST BOOL 0x0001 0x0000\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                bool_case(&[true, true], false),
                bool_case(&[true, false], true),
                bool_case(&[false, true], true),
                bool_case(&[false, false], true),
            ],
            category: Category::BooleanLogic,
        },
        // ex075: nor (NOT (a OR b))
        ProgramSpec {
            id: "ex075_nor",
            intent: "Logical NOR of two booleans",
            assembly_template: concat!(
                "FUNC 2 8\n",
                "PARAM BOOL\n",
                "PARAM BOOL\n",
                "REF 1\n",
                "REF 0\n",
                "OR\n",
                "NOT\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST BOOL 0x0000 0x0000\n",
                "CONST BOOL 0x0000 0x0000\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                bool_case(&[false, false], true),
                bool_case(&[true, false], false),
                bool_case(&[false, true], false),
                bool_case(&[true, true], false),
            ],
            category: Category::BooleanLogic,
        },
        // ex076: implies (a IMPLIES b)
        ProgramSpec {
            id: "ex076_implies",
            intent: "Logical implication: if a then b",
            assembly_template: concat!(
                "FUNC 2 7\n",
                "PARAM BOOL\n",
                "PARAM BOOL\n",
                "REF 1\n",
                "REF 0\n",
                "IMPLIES\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST BOOL 0x0001 0x0000\n",
                "CONST BOOL 0x0001 0x0000\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                bool_case(&[true, true], true),
                bool_case(&[true, false], false),
                bool_case(&[false, true], true),
                bool_case(&[false, false], true),
            ],
            category: Category::BooleanLogic,
        },
        // ex077: equiv (a == b)
        ProgramSpec {
            id: "ex077_equiv",
            intent: "Logical equivalence of two booleans",
            assembly_template: concat!(
                "FUNC 2 7\n",
                "PARAM BOOL\n",
                "PARAM BOOL\n",
                "REF 1\n",
                "REF 0\n",
                "EQ\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST BOOL 0x0001 0x0000\n",
                "CONST BOOL 0x0001 0x0000\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                bool_case(&[true, true], true),
                bool_case(&[false, false], true),
                bool_case(&[true, false], false),
                bool_case(&[false, true], false),
            ],
            category: Category::BooleanLogic,
        },
        // ex078: majority ((a AND b) OR (a AND c) OR (b AND c))
        ProgramSpec {
            id: "ex078_majority",
            intent: "Majority vote of three booleans",
            assembly_template: concat!(
                "FUNC 3 16\n",
                "PARAM BOOL\n",
                "PARAM BOOL\n",
                "PARAM BOOL\n",
                "REF 2\n",
                "REF 1\n",
                "AND\n",
                "REF 2\n",
                "REF 0\n",
                "AND\n",
                "OR\n",
                "REF 1\n",
                "REF 0\n",
                "AND\n",
                "OR\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST BOOL 0x0001 0x0000\n",
                "CONST BOOL 0x0001 0x0000\n",
                "CONST BOOL 0x0000 0x0000\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                bool_case(&[true, true, false], true),
                bool_case(&[true, false, true], true),
                bool_case(&[false, true, true], true),
                bool_case(&[true, false, false], false),
            ],
            category: Category::BooleanLogic,
        },
        // ex079: any_true (a OR b OR c)
        ProgramSpec {
            id: "ex079_any_true",
            intent: "Check if any of three booleans is true",
            assembly_template: concat!(
                "FUNC 3 10\n",
                "PARAM BOOL\n",
                "PARAM BOOL\n",
                "PARAM BOOL\n",
                "REF 2\n",
                "REF 1\n",
                "OR\n",
                "REF 0\n",
                "OR\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST BOOL 0x0000 0x0000\n",
                "CONST BOOL 0x0001 0x0000\n",
                "CONST BOOL 0x0000 0x0000\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                bool_case(&[false, true, false], true),
                bool_case(&[true, false, false], true),
                bool_case(&[false, false, false], false),
                bool_case(&[true, true, true], true),
            ],
            category: Category::BooleanLogic,
        },
        // ex080: all_true (a AND b AND c)
        ProgramSpec {
            id: "ex080_all_true",
            intent: "Check if all three booleans are true",
            assembly_template: concat!(
                "FUNC 3 10\n",
                "PARAM BOOL\n",
                "PARAM BOOL\n",
                "PARAM BOOL\n",
                "REF 2\n",
                "REF 1\n",
                "AND\n",
                "REF 0\n",
                "AND\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST BOOL 0x0001 0x0000\n",
                "CONST BOOL 0x0001 0x0000\n",
                "CONST BOOL 0x0001 0x0000\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                bool_case(&[true, true, true], true),
                bool_case(&[true, true, false], false),
                bool_case(&[true, false, true], false),
                bool_case(&[false, false, false], false),
            ],
            category: Category::BooleanLogic,
        },
        // ex081: none_true (NOT a AND NOT b AND NOT c)
        ProgramSpec {
            id: "ex081_none_true",
            intent: "Check if all three booleans are false",
            assembly_template: concat!(
                "FUNC 3 13\n",
                "PARAM BOOL\n",
                "PARAM BOOL\n",
                "PARAM BOOL\n",
                "REF 2\n",
                "NOT\n",
                "REF 1\n",
                "NOT\n",
                "AND\n",
                "REF 0\n",
                "NOT\n",
                "AND\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST BOOL 0x0000 0x0000\n",
                "CONST BOOL 0x0000 0x0000\n",
                "CONST BOOL 0x0000 0x0000\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                bool_case(&[false, false, false], true),
                bool_case(&[true, false, false], false),
                bool_case(&[false, true, false], false),
                bool_case(&[false, false, true], false),
            ],
            category: Category::BooleanLogic,
        },
        // ex082: exactly_one (a XOR b)
        ProgramSpec {
            id: "ex082_exactly_one",
            intent: "Check if exactly one of two booleans is true",
            assembly_template: concat!(
                "FUNC 2 7\n",
                "PARAM BOOL\n",
                "PARAM BOOL\n",
                "REF 1\n",
                "REF 0\n",
                "XOR\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST BOOL 0x0001 0x0000\n",
                "CONST BOOL 0x0000 0x0000\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                bool_case(&[true, false], true),
                bool_case(&[false, true], true),
                bool_case(&[true, true], false),
                bool_case(&[false, false], false),
            ],
            category: Category::BooleanLogic,
        },
        // ex083: bool_mux (if sel then a else b)
        ProgramSpec {
            id: "ex083_bool_mux",
            intent: "Select between two integers based on a boolean selector",
            assembly_template: concat!(
                "FUNC 3 12\n",
                "PARAM BOOL\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 2\n",
                "MATCH 2\n",
                "CASE 0 1\n",
                "REF 0\n",
                "CASE 1 1\n",
                "REF 1\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST BOOL 0x0001 0x0000\n",
                "CONST I64 0x0000 0x000a\n",
                "CONST I64 0x0000 0x0014\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                WitnessCase {
                    inputs: vec![
                        WitnessValue::Bool(true),
                        WitnessValue::I64(10),
                        WitnessValue::I64(20),
                    ],
                    expected: WitnessValue::I64(10),
                },
                WitnessCase {
                    inputs: vec![
                        WitnessValue::Bool(false),
                        WitnessValue::I64(10),
                        WitnessValue::I64(20),
                    ],
                    expected: WitnessValue::I64(20),
                },
                WitnessCase {
                    inputs: vec![
                        WitnessValue::Bool(true),
                        WitnessValue::I64(0),
                        WitnessValue::I64(100),
                    ],
                    expected: WitnessValue::I64(0),
                },
            ],
            category: Category::BooleanLogic,
        },
        // ex084: bool_to_int (if a then 1 else 0)
        ProgramSpec {
            id: "ex084_bool_to_int",
            intent: "Convert a boolean to an integer: true becomes 1, false becomes 0",
            assembly_template: concat!(
                "FUNC 1 10\n",
                "PARAM BOOL\n",
                "REF 0\n",
                "MATCH 2\n",
                "CASE 0 1\n",
                "CONST I64 0x0000 0x0000\n",
                "CASE 1 1\n",
                "CONST I64 0x0000 0x0001\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST BOOL 0x0001 0x0000\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![bool_to_i64_case(&[true], 1), bool_to_i64_case(&[false], 0)],
            category: Category::BooleanLogic,
        },
    ]
}
