//! Comparison programs (20): ex050-ex069.

use super::{i64_to_bool_case, Category, ProgramSpec};

pub fn programs() -> Vec<ProgramSpec> {
    vec![
        // ex050: is_positive (x > 0)
        ProgramSpec {
            id: "ex050_is_positive",
            intent: "Check if an integer is positive",
            assembly_template: concat!(
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "GT\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[5], true),
                i64_to_bool_case(&[0], false),
                i64_to_bool_case(&[-3], false),
                i64_to_bool_case(&[1], true),
            ],
            category: Category::Comparison,
        },
        // ex051: is_negative (x < 0)
        ProgramSpec {
            id: "ex051_is_negative",
            intent: "Check if an integer is negative",
            assembly_template: concat!(
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "LT\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0xffff 0xfffe\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[-2], true),
                i64_to_bool_case(&[0], false),
                i64_to_bool_case(&[3], false),
                i64_to_bool_case(&[-100], true),
            ],
            category: Category::Comparison,
        },
        // ex052: is_nonneg (x >= 0)
        ProgramSpec {
            id: "ex052_is_nonneg",
            intent: "Check if an integer is non-negative",
            assembly_template: concat!(
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "GTE\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0000\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[0], true),
                i64_to_bool_case(&[5], true),
                i64_to_bool_case(&[-1], false),
                i64_to_bool_case(&[100], true),
            ],
            category: Category::Comparison,
        },
        // ex053: is_nonpos (x <= 0)
        ProgramSpec {
            id: "ex053_is_nonpos",
            intent: "Check if an integer is non-positive",
            assembly_template: concat!(
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "LTE\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0000\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[0], true),
                i64_to_bool_case(&[-5], true),
                i64_to_bool_case(&[1], false),
                i64_to_bool_case(&[-100], true),
            ],
            category: Category::Comparison,
        },
        // ex054: equals (a == b)
        ProgramSpec {
            id: "ex054_equals",
            intent: "Check if two integers are equal",
            assembly_template: concat!(
                "FUNC 2 7\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "EQ\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CONST I64 0x0000 0x0005\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[5, 5], true),
                i64_to_bool_case(&[3, 5], false),
                i64_to_bool_case(&[0, 0], true),
                i64_to_bool_case(&[-1, -1], true),
            ],
            category: Category::Comparison,
        },
        // ex055: not_equals (a != b)
        ProgramSpec {
            id: "ex055_not_equals",
            intent: "Check if two integers are not equal",
            assembly_template: concat!(
                "FUNC 2 7\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "NEQ\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[5, 3], true),
                i64_to_bool_case(&[5, 5], false),
                i64_to_bool_case(&[0, 1], true),
                i64_to_bool_case(&[-1, -1], false),
            ],
            category: Category::Comparison,
        },
        // ex056: less_than (a < b)
        ProgramSpec {
            id: "ex056_less_than",
            intent: "Check if the first integer is less than the second",
            assembly_template: concat!(
                "FUNC 2 7\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "LT\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0003\n",
                "CONST I64 0x0000 0x0005\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[3, 5], true),
                i64_to_bool_case(&[5, 3], false),
                i64_to_bool_case(&[5, 5], false),
                i64_to_bool_case(&[-1, 0], true),
            ],
            category: Category::Comparison,
        },
        // ex057: greater_than (a > b)
        ProgramSpec {
            id: "ex057_greater_than",
            intent: "Check if the first integer is greater than the second",
            assembly_template: concat!(
                "FUNC 2 7\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "GT\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[5, 3], true),
                i64_to_bool_case(&[3, 5], false),
                i64_to_bool_case(&[5, 5], false),
                i64_to_bool_case(&[0, -1], true),
            ],
            category: Category::Comparison,
        },
        // ex058: in_range (lo <= x AND x <= hi)
        ProgramSpec {
            id: "ex058_in_range",
            intent: "Check if an integer is within a range (inclusive)",
            assembly_template: concat!(
                "FUNC 3 12\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 2\n",
                "LTE\n",
                "REF 2\n",
                "REF 0\n",
                "LTE\n",
                "AND\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CONST I64 0x0000 0x0001\n",
                "CONST I64 0x0000 0x000a\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[5, 1, 10], true),
                i64_to_bool_case(&[0, 1, 10], false),
                i64_to_bool_case(&[1, 1, 10], true),
                i64_to_bool_case(&[10, 1, 10], true),
            ],
            category: Category::Comparison,
        },
        // ex059: out_of_range (x < lo OR x > hi)
        ProgramSpec {
            id: "ex059_out_of_range",
            intent: "Check if an integer is outside a range",
            assembly_template: concat!(
                "FUNC 3 12\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 2\n",
                "REF 1\n",
                "LT\n",
                "REF 2\n",
                "REF 0\n",
                "GT\n",
                "OR\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0000\n",
                "CONST I64 0x0000 0x0001\n",
                "CONST I64 0x0000 0x000a\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[0, 1, 10], true),
                i64_to_bool_case(&[11, 1, 10], true),
                i64_to_bool_case(&[5, 1, 10], false),
                i64_to_bool_case(&[1, 1, 10], false),
            ],
            category: Category::Comparison,
        },
        // ex060: same_sign ((a>=0 AND b>=0) OR (a<0 AND b<0))
        ProgramSpec {
            id: "ex060_same_sign",
            intent: "Check if two integers have the same sign",
            assembly_template: concat!(
                "FUNC 2 19\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "CONST I64 0x0000 0x0000\n",
                "GTE\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "GTE\n",
                "AND\n",
                "REF 1\n",
                "CONST I64 0x0000 0x0000\n",
                "LT\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "LT\n",
                "AND\n",
                "OR\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[5, 3], true),
                i64_to_bool_case(&[-5, -3], true),
                i64_to_bool_case(&[5, -3], false),
                i64_to_bool_case(&[0, 5], true),
            ],
            category: Category::Comparison,
        },
        // ex061: both_positive (a > 0 AND b > 0)
        ProgramSpec {
            id: "ex061_both_positive",
            intent: "Check if both integers are positive",
            assembly_template: concat!(
                "FUNC 2 11\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "CONST I64 0x0000 0x0000\n",
                "GT\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "GT\n",
                "AND\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[5, 3], true),
                i64_to_bool_case(&[0, 3], false),
                i64_to_bool_case(&[-1, 3], false),
                i64_to_bool_case(&[1, 1], true),
            ],
            category: Category::Comparison,
        },
        // ex062: both_negative (a < 0 AND b < 0)
        ProgramSpec {
            id: "ex062_both_negative",
            intent: "Check if both integers are negative",
            assembly_template: concat!(
                "FUNC 2 11\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "CONST I64 0x0000 0x0000\n",
                "LT\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "LT\n",
                "AND\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0xffff 0xfffb\n",
                "CONST I64 0xffff 0xfffd\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[-5, -3], true),
                i64_to_bool_case(&[0, -3], false),
                i64_to_bool_case(&[5, -3], false),
                i64_to_bool_case(&[-1, -1], true),
            ],
            category: Category::Comparison,
        },
        // ex063: either_zero (a == 0 OR b == 0)
        ProgramSpec {
            id: "ex063_either_zero",
            intent: "Check if at least one of two integers is zero",
            assembly_template: concat!(
                "FUNC 2 11\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "CONST I64 0x0000 0x0000\n",
                "EQ\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "EQ\n",
                "OR\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0000\n",
                "CONST I64 0x0000 0x0005\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[0, 5], true),
                i64_to_bool_case(&[5, 0], true),
                i64_to_bool_case(&[0, 0], true),
                i64_to_bool_case(&[5, 3], false),
            ],
            category: Category::Comparison,
        },
        // ex064: all_equal_three (a == b AND b == c)
        ProgramSpec {
            id: "ex064_all_equal_three",
            intent: "Check if three integers are all equal",
            assembly_template: concat!(
                "FUNC 3 12\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 2\n",
                "REF 1\n",
                "EQ\n",
                "REF 1\n",
                "REF 0\n",
                "EQ\n",
                "AND\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CONST I64 0x0000 0x0005\n",
                "CONST I64 0x0000 0x0005\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[5, 5, 5], true),
                i64_to_bool_case(&[5, 5, 3], false),
                i64_to_bool_case(&[5, 3, 5], false),
                i64_to_bool_case(&[0, 0, 0], true),
            ],
            category: Category::Comparison,
        },
        // ex065: between_exclusive (lo < x AND x < hi)
        ProgramSpec {
            id: "ex065_between_exclusive",
            intent: "Check if an integer is strictly between two bounds",
            assembly_template: concat!(
                "FUNC 3 12\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 2\n",
                "LT\n",
                "REF 2\n",
                "REF 0\n",
                "LT\n",
                "AND\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CONST I64 0x0000 0x0001\n",
                "CONST I64 0x0000 0x000a\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[5, 1, 10], true),
                i64_to_bool_case(&[1, 1, 10], false),
                i64_to_bool_case(&[10, 1, 10], false),
                i64_to_bool_case(&[0, 1, 10], false),
            ],
            category: Category::Comparison,
        },
        // ex066: ordered_triple (a <= b AND b <= c)
        ProgramSpec {
            id: "ex066_ordered_triple",
            intent: "Check if three integers are in non-decreasing order",
            assembly_template: concat!(
                "FUNC 3 12\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 2\n",
                "REF 1\n",
                "LTE\n",
                "REF 1\n",
                "REF 0\n",
                "LTE\n",
                "AND\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0001\n",
                "CONST I64 0x0000 0x0005\n",
                "CONST I64 0x0000 0x000a\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[1, 5, 10], true),
                i64_to_bool_case(&[5, 1, 10], false),
                i64_to_bool_case(&[1, 10, 5], false),
                i64_to_bool_case(&[5, 5, 5], true),
            ],
            category: Category::Comparison,
        },
        // ex067: compare_abs (a*a > b*b)
        ProgramSpec {
            id: "ex067_compare_abs",
            intent: "Check if the absolute value of the first integer is greater than the second",
            assembly_template: concat!(
                "FUNC 2 11\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 1\n",
                "MUL\n",
                "REF 0\n",
                "REF 0\n",
                "MUL\n",
                "GT\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0xffff 0xfffb\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[-5, 3], true),
                i64_to_bool_case(&[5, 3], true),
                i64_to_bool_case(&[3, 5], false),
                i64_to_bool_case(&[3, 3], false),
            ],
            category: Category::Comparison,
        },
        // ex068: is_unit_value (x == 1)
        ProgramSpec {
            id: "ex068_is_unit_value",
            intent: "Check if an integer equals one",
            assembly_template: concat!(
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "EQ\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0001\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[1], true),
                i64_to_bool_case(&[0], false),
                i64_to_bool_case(&[-1], false),
                i64_to_bool_case(&[2], false),
            ],
            category: Category::Comparison,
        },
        // ex069: is_multiple_of (a % b == 0)
        ProgramSpec {
            id: "ex069_is_multiple_of",
            intent: "Check if the first integer is a multiple of the second",
            assembly_template: concat!(
                "FUNC 2 9\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "MOD\n",
                "CONST I64 0x0000 0x0000\n",
                "EQ\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x000a\n",
                "CONST I64 0x0000 0x0005\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[10, 5], true),
                i64_to_bool_case(&[10, 3], false),
                i64_to_bool_case(&[0, 5], true),
                i64_to_bool_case(&[15, 3], true),
            ],
            category: Category::Comparison,
        },
    ]
}
