//! Integer math programs (30): ex020-ex049.

use super::{i64_case, i64_to_bool_case, Category, ProgramSpec};

pub fn programs() -> Vec<ProgramSpec> {
    vec![
        // ex020: square (x → x²)
        ProgramSpec {
            id: "ex020_square",
            intent: "Compute the square of an integer",
            assembly_template: concat!(
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "REF 0\n",
                "MUL\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[5], 25),
                i64_case(&[0], 0),
                i64_case(&[-3], 9),
                i64_case(&[1], 1),
            ],
            category: Category::IntegerMath,
        },
        // ex021: cube (x → x³)
        ProgramSpec {
            id: "ex021_cube",
            intent: "Compute the cube of an integer",
            assembly_template: concat!(
                "FUNC 1 8\n",
                "PARAM I64\n",
                "REF 0\n",
                "REF 0\n",
                "MUL\n",
                "REF 0\n",
                "MUL\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[3], 27),
                i64_case(&[0], 0),
                i64_case(&[-2], -8),
                i64_case(&[1], 1),
            ],
            category: Category::IntegerMath,
        },
        // ex022: double (x → 2x)
        ProgramSpec {
            id: "ex022_double",
            intent: "Double an integer",
            assembly_template: concat!(
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "REF 0\n",
                "ADD\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0007\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[7], 14),
                i64_case(&[0], 0),
                i64_case(&[-5], -10),
                i64_case(&[1], 2),
            ],
            category: Category::IntegerMath,
        },
        // ex023: triple (x → 3x)
        ProgramSpec {
            id: "ex023_triple",
            intent: "Triple an integer",
            assembly_template: concat!(
                "FUNC 1 8\n",
                "PARAM I64\n",
                "REF 0\n",
                "REF 0\n",
                "ADD\n",
                "REF 0\n",
                "ADD\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0004\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[4], 12),
                i64_case(&[0], 0),
                i64_case(&[-3], -9),
                i64_case(&[1], 3),
            ],
            category: Category::IntegerMath,
        },
        // ex024: add two (a, b → a+b)
        ProgramSpec {
            id: "ex024_add_two",
            intent: "Add two integers",
            assembly_template: concat!(
                "FUNC 2 7\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "ADD\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[5, 3], 8),
                i64_case(&[0, 0], 0),
                i64_case(&[-1, 1], 0),
                i64_case(&[100, -50], 50),
            ],
            category: Category::IntegerMath,
        },
        // ex025: subtract two (a, b → a-b)
        ProgramSpec {
            id: "ex025_sub_two",
            intent: "Subtract the second integer from the first",
            assembly_template: concat!(
                "FUNC 2 7\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "SUB\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[5, 3], 2),
                i64_case(&[3, 5], -2),
                i64_case(&[0, 0], 0),
                i64_case(&[10, 10], 0),
            ],
            category: Category::IntegerMath,
        },
        // ex026: multiply two (a, b → a*b)
        ProgramSpec {
            id: "ex026_mul_two",
            intent: "Multiply two integers",
            assembly_template: concat!(
                "FUNC 2 7\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "MUL\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[5, 3], 15),
                i64_case(&[0, 7], 0),
                i64_case(&[-2, 4], -8),
                i64_case(&[1, 1], 1),
            ],
            category: Category::IntegerMath,
        },
        // ex027: divide two (a, b → a/b)
        ProgramSpec {
            id: "ex027_div_two",
            intent: "Divide first integer by second (integer division)",
            assembly_template: concat!(
                "FUNC 2 7\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "DIV\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x000a\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[10, 3], 3),
                i64_case(&[7, 2], 3),
                i64_case(&[6, 3], 2),
                i64_case(&[100, 10], 10),
            ],
            category: Category::IntegerMath,
        },
        // ex028: modulo two (a, b → a%b)
        ProgramSpec {
            id: "ex028_mod_two",
            intent: "Compute the remainder of dividing first integer by second",
            assembly_template: concat!(
                "FUNC 2 7\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "MOD\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x000a\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[10, 3], 1),
                i64_case(&[7, 2], 1),
                i64_case(&[6, 3], 0),
                i64_case(&[17, 5], 2),
            ],
            category: Category::IntegerMath,
        },
        // ex029: negate (x → -x)
        ProgramSpec {
            id: "ex029_negate",
            intent: "Negate an integer",
            assembly_template: concat!(
                "FUNC 1 5\n",
                "PARAM I64\n",
                "REF 0\n",
                "NEG\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[5], -5),
                i64_case(&[-3], 3),
                i64_case(&[0], 0),
                i64_case(&[1], -1),
            ],
            category: Category::IntegerMath,
        },
        // ex030: sum of squares (a, b → a²+b²)
        ProgramSpec {
            id: "ex030_sum_of_squares",
            intent: "Compute the sum of squares of two integers",
            assembly_template: concat!(
                "FUNC 2 11\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 1\n",
                "MUL\n",
                "REF 0\n",
                "REF 0\n",
                "MUL\n",
                "ADD\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0003\n",
                "CONST I64 0x0000 0x0004\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[3, 4], 25),
                i64_case(&[0, 5], 25),
                i64_case(&[1, 1], 2),
                i64_case(&[2, 3], 13),
            ],
            category: Category::IntegerMath,
        },
        // ex031: difference of squares (a, b → a²-b²)
        ProgramSpec {
            id: "ex031_diff_of_squares",
            intent: "Compute the difference of squares of two integers",
            assembly_template: concat!(
                "FUNC 2 11\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 1\n",
                "MUL\n",
                "REF 0\n",
                "REF 0\n",
                "MUL\n",
                "SUB\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[5, 3], 16),
                i64_case(&[3, 5], -16),
                i64_case(&[4, 4], 0),
                i64_case(&[1, 0], 1),
            ],
            category: Category::IntegerMath,
        },
        // ex032: average (a, b → (a+b)/2)
        ProgramSpec {
            id: "ex032_average",
            intent: "Compute the integer average of two numbers",
            assembly_template: concat!(
                "FUNC 2 9\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "ADD\n",
                "CONST I64 0x0000 0x0002\n",
                "DIV\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x000a\n",
                "CONST I64 0x0000 0x0006\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[10, 6], 8),
                i64_case(&[7, 3], 5),
                i64_case(&[0, 0], 0),
                i64_case(&[1, 1], 1),
            ],
            category: Category::IntegerMath,
        },
        // ex033: distance (a, b → |a-b|) using recomputation
        ProgramSpec {
            id: "ex033_distance",
            intent: "Compute the absolute difference between two integers",
            assembly_template: concat!(
                "FUNC 2 19\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "SUB\n",
                "CONST I64 0x0000 0x0000\n",
                "LT\n",
                "MATCH 2\n",
                "CASE 0 3\n",
                "REF 1\n",
                "REF 0\n",
                "SUB\n",
                "CASE 1 3\n",
                "REF 0\n",
                "REF 1\n",
                "SUB\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[5, 3], 2),
                i64_case(&[3, 5], 2),
                i64_case(&[0, 0], 0),
                i64_case(&[10, 3], 7),
            ],
            category: Category::IntegerMath,
        },
        // ex034: power of two (n → 2^n) recursive
        ProgramSpec {
            id: "ex034_power_of_two",
            intent: "Compute 2 raised to the power n using recursion",
            assembly_template: concat!(
                "FUNC 1 17\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "LTE\n",
                "MATCH 2\n",
                "CASE 0 6\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "SUB\n",
                "RECURSE 100\n",
                "CONST I64 0x0000 0x0002\n",
                "MUL\n",
                "CASE 1 1\n",
                "CONST I64 0x0000 0x0001\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[5], 32),
                i64_case(&[0], 1),
                i64_case(&[1], 2),
                i64_case(&[10], 1024),
            ],
            category: Category::IntegerMath,
        },
        // ex035: increment (x → x+1)
        ProgramSpec {
            id: "ex035_increment",
            intent: "Add one to an integer",
            assembly_template: concat!(
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "ADD\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[5], 6),
                i64_case(&[0], 1),
                i64_case(&[-1], 0),
                i64_case(&[99], 100),
            ],
            category: Category::IntegerMath,
        },
        // ex036: decrement (x → x-1)
        ProgramSpec {
            id: "ex036_decrement",
            intent: "Subtract one from an integer",
            assembly_template: concat!(
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "SUB\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[5], 4),
                i64_case(&[0], -1),
                i64_case(&[1], 0),
                i64_case(&[100], 99),
            ],
            category: Category::IntegerMath,
        },
        // ex037: is even (x → x%2==0)
        ProgramSpec {
            id: "ex037_is_even",
            intent: "Check if an integer is even",
            assembly_template: concat!(
                "FUNC 1 8\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0002\n",
                "MOD\n",
                "CONST I64 0x0000 0x0000\n",
                "EQ\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0004\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[4], true),
                i64_to_bool_case(&[3], false),
                i64_to_bool_case(&[0], true),
                i64_to_bool_case(&[1], false),
            ],
            category: Category::IntegerMath,
        },
        // ex038: is odd (x → x%2!=0)
        ProgramSpec {
            id: "ex038_is_odd",
            intent: "Check if an integer is odd",
            assembly_template: concat!(
                "FUNC 1 8\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0002\n",
                "MOD\n",
                "CONST I64 0x0000 0x0000\n",
                "NEQ\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[3], true),
                i64_to_bool_case(&[4], false),
                i64_to_bool_case(&[0], false),
                i64_to_bool_case(&[1], true),
            ],
            category: Category::IntegerMath,
        },
        // ex039: is zero (x → x==0)
        ProgramSpec {
            id: "ex039_is_zero",
            intent: "Check if an integer is zero",
            assembly_template: concat!(
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "EQ\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0000\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[0], true),
                i64_to_bool_case(&[1], false),
                i64_to_bool_case(&[-1], false),
                i64_to_bool_case(&[42], false),
            ],
            category: Category::IntegerMath,
        },
        // ex040: halve (x → x/2)
        ProgramSpec {
            id: "ex040_halve",
            intent: "Divide an integer by two",
            assembly_template: concat!(
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0002\n",
                "DIV\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x000a\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[10], 5),
                i64_case(&[6], 3),
                i64_case(&[0], 0),
                i64_case(&[100], 50),
            ],
            category: Category::IntegerMath,
        },
        // ex041: quadruple (x → 4x)
        ProgramSpec {
            id: "ex041_quadruple",
            intent: "Multiply an integer by four",
            assembly_template: concat!(
                "FUNC 1 10\n",
                "PARAM I64\n",
                "REF 0\n",
                "REF 0\n",
                "ADD\n",
                "REF 0\n",
                "REF 0\n",
                "ADD\n",
                "ADD\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[3], 12),
                i64_case(&[0], 0),
                i64_case(&[1], 4),
                i64_case(&[-2], -8),
            ],
            category: Category::IntegerMath,
        },
        // ex042: sum three (a, b, c → a+b+c)
        ProgramSpec {
            id: "ex042_sum_three",
            intent: "Add three integers",
            assembly_template: concat!(
                "FUNC 3 10\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 2\n",
                "REF 1\n",
                "ADD\n",
                "REF 0\n",
                "ADD\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0001\n",
                "CONST I64 0x0000 0x0002\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[1, 2, 3], 6),
                i64_case(&[0, 0, 0], 0),
                i64_case(&[-1, 1, 0], 0),
                i64_case(&[10, 20, 30], 60),
            ],
            category: Category::IntegerMath,
        },
        // ex043: product three (a, b, c → a*b*c)
        ProgramSpec {
            id: "ex043_product_three",
            intent: "Multiply three integers",
            assembly_template: concat!(
                "FUNC 3 10\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 2\n",
                "REF 1\n",
                "MUL\n",
                "REF 0\n",
                "MUL\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0002\n",
                "CONST I64 0x0000 0x0003\n",
                "CONST I64 0x0000 0x0004\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[2, 3, 4], 24),
                i64_case(&[1, 1, 1], 1),
                i64_case(&[0, 5, 10], 0),
                i64_case(&[2, 5, 10], 100),
            ],
            category: Category::IntegerMath,
        },
        // ex044: max of three (a, b, c → max)
        // input[0]=a pushed first (REF 2), input[1]=b (REF 1), input[2]=c (REF 0)
        ProgramSpec {
            id: "ex044_max_of_three",
            intent: "Find the maximum of three integers",
            assembly_template: concat!(
                "FUNC 3 30\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 2\n",
                "REF 1\n",
                "GTE\n",
                "MATCH 2\n",
                "CASE 0 9\n",
                "REF 1\n",
                "REF 0\n",
                "GTE\n",
                "MATCH 2\n",
                "CASE 0 1\n",
                "REF 0\n",
                "CASE 1 1\n",
                "REF 1\n",
                "EXHAUST\n",
                "CASE 1 9\n",
                "REF 2\n",
                "REF 0\n",
                "GTE\n",
                "MATCH 2\n",
                "CASE 0 1\n",
                "REF 0\n",
                "CASE 1 1\n",
                "REF 2\n",
                "EXHAUST\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CONST I64 0x0000 0x0003\n",
                "CONST I64 0x0000 0x0001\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[5, 3, 1], 5),
                i64_case(&[1, 3, 5], 5),
                i64_case(&[3, 5, 1], 5),
                i64_case(&[7, 7, 7], 7),
            ],
            category: Category::IntegerMath,
        },
        // ex045: min of three (a, b, c → min)
        ProgramSpec {
            id: "ex045_min_of_three",
            intent: "Find the minimum of three integers",
            assembly_template: concat!(
                "FUNC 3 30\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 2\n",
                "REF 1\n",
                "LTE\n",
                "MATCH 2\n",
                "CASE 0 9\n",
                "REF 1\n",
                "REF 0\n",
                "LTE\n",
                "MATCH 2\n",
                "CASE 0 1\n",
                "REF 0\n",
                "CASE 1 1\n",
                "REF 1\n",
                "EXHAUST\n",
                "CASE 1 9\n",
                "REF 2\n",
                "REF 0\n",
                "LTE\n",
                "MATCH 2\n",
                "CASE 0 1\n",
                "REF 0\n",
                "CASE 1 1\n",
                "REF 2\n",
                "EXHAUST\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CONST I64 0x0000 0x0003\n",
                "CONST I64 0x0000 0x0001\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[5, 3, 1], 1),
                i64_case(&[1, 3, 5], 1),
                i64_case(&[3, 1, 5], 1),
                i64_case(&[7, 7, 7], 7),
            ],
            category: Category::IntegerMath,
        },
        // ex046: midpoint (a, b → (a+b)/2)
        ProgramSpec {
            id: "ex046_midpoint",
            intent: "Compute the midpoint of two integers",
            assembly_template: concat!(
                "FUNC 2 9\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "ADD\n",
                "CONST I64 0x0000 0x0002\n",
                "DIV\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0004\n",
                "CONST I64 0x0000 0x000a\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[4, 10], 7),
                i64_case(&[0, 8], 4),
                i64_case(&[3, 3], 3),
                i64_case(&[0, 0], 0),
            ],
            category: Category::IntegerMath,
        },
        // ex047: multiply-add (a, b, c → a*b+c)
        ProgramSpec {
            id: "ex047_multiply_add",
            intent: "Compute a times b plus c",
            assembly_template: concat!(
                "FUNC 3 10\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 2\n",
                "REF 1\n",
                "MUL\n",
                "REF 0\n",
                "ADD\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0002\n",
                "CONST I64 0x0000 0x0003\n",
                "CONST I64 0x0000 0x0004\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[2, 3, 4], 10),
                i64_case(&[0, 5, 7], 7),
                i64_case(&[1, 1, 1], 2),
                i64_case(&[3, 4, 5], 17),
            ],
            category: Category::IntegerMath,
        },
        // ex048: remainder check (a, b → a%b==0)
        ProgramSpec {
            id: "ex048_remainder_check",
            intent: "Check if the first integer is divisible by the second",
            assembly_template: concat!(
                "FUNC 2 9\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "MOD\n",
                "CONST I64 0x0000 0x0000\n",
                "EQ\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x000a\n",
                "CONST I64 0x0000 0x0005\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[10, 5], true),
                i64_to_bool_case(&[10, 3], false),
                i64_to_bool_case(&[0, 1], true),
                i64_to_bool_case(&[6, 3], true),
            ],
            category: Category::IntegerMath,
        },
        // ex049: squared sum (a, b → (a+b)²)
        ProgramSpec {
            id: "ex049_squared_sum",
            intent: "Compute the square of the sum of two integers",
            assembly_template: concat!(
                "FUNC 2 11\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "ADD\n",
                "REF 1\n",
                "REF 0\n",
                "ADD\n",
                "MUL\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0003\n",
                "CONST I64 0x0000 0x0004\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[3, 4], 49),
                i64_case(&[1, 1], 4),
                i64_case(&[0, 5], 25),
                i64_case(&[2, 3], 25),
            ],
            category: Category::IntegerMath,
        },
    ]
}
