//! Multi-function programs (15): ex185-ex199.
//!
//! Programs with 2+ FUNC blocks demonstrating function composition.

use super::{i64_case, i64_to_bool_case, Category, ProgramSpec};

pub fn programs() -> Vec<ProgramSpec> {
    vec![
        // ex185: abs + double (two functions, witnesses test abs)
        ProgramSpec {
            id: "ex185_abs_double",
            intent: "Define abs and double functions",
            assembly_template: concat!(
                "FUNC 1 13\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "LT\n",
                "MATCH 2\n",
                "CASE 0 1\n",
                "REF 0\n",
                "CASE 1 2\n",
                "REF 0\n",
                "NEG\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "REF 0\n",
                "ADD\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0xffff 0xfffd\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[-3], 3),
                i64_case(&[5], 5),
                i64_case(&[0], 0),
                i64_case(&[-10], 10),
            ],
            category: Category::MultiFunction,
        },
        // ex186: square + add_one
        ProgramSpec {
            id: "ex186_square_add",
            intent: "Define square and add_one functions",
            assembly_template: concat!(
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "REF 0\n",
                "MUL\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "ADD\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[3], 9),
                i64_case(&[0], 0),
                i64_case(&[-2], 4),
                i64_case(&[5], 25),
            ],
            category: Category::MultiFunction,
        },
        // ex187: negate + double
        ProgramSpec {
            id: "ex187_negate_double",
            intent: "Define negate and double functions",
            assembly_template: concat!(
                "FUNC 1 5\n",
                "PARAM I64\n",
                "REF 0\n",
                "NEG\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "REF 0\n",
                "ADD\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[5], -5),
                i64_case(&[0], 0),
                i64_case(&[-3], 3),
                i64_case(&[10], -10),
            ],
            category: Category::MultiFunction,
        },
        // ex188: increment + decrement
        ProgramSpec {
            id: "ex188_increment_decrement",
            intent: "Define increment and decrement functions",
            assembly_template: concat!(
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "ADD\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "SUB\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[5], 6),
                i64_case(&[0], 1),
                i64_case(&[-1], 0),
                i64_case(&[99], 100),
            ],
            category: Category::MultiFunction,
        },
        // ex189: halve + double
        ProgramSpec {
            id: "ex189_halve_double",
            intent: "Define halve and double functions",
            assembly_template: concat!(
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0002\n",
                "DIV\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "REF 0\n",
                "ADD\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x000a\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[10], 5),
                i64_case(&[6], 3),
                i64_case(&[0], 0),
                i64_case(&[100], 50),
            ],
            category: Category::MultiFunction,
        },
        // ex190: add + subtract (2 params each)
        ProgramSpec {
            id: "ex190_add_sub",
            intent: "Define add and subtract functions",
            assembly_template: concat!(
                "FUNC 2 7\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "ADD\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "FUNC 2 7\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "SUB\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[5, 3], 8),
                i64_case(&[0, 0], 0),
                i64_case(&[-1, 1], 0),
                i64_case(&[100, -50], 50),
            ],
            category: Category::MultiFunction,
        },
        // ex191: multiply + divide
        ProgramSpec {
            id: "ex191_mul_div",
            intent: "Define multiply and divide functions",
            assembly_template: concat!(
                "FUNC 2 7\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "MUL\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "FUNC 2 7\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "DIV\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[5, 3], 15),
                i64_case(&[0, 7], 0),
                i64_case(&[-2, 4], -8),
                i64_case(&[1, 1], 1),
            ],
            category: Category::MultiFunction,
        },
        // ex192: min + max
        ProgramSpec {
            id: "ex192_min_max",
            intent: "Define min and max functions",
            assembly_template: concat!(
                "FUNC 2 13\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "LT\n",
                "MATCH 2\n",
                "CASE 0 1\n",
                "REF 0\n",
                "CASE 1 1\n",
                "REF 1\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "FUNC 2 13\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "GT\n",
                "MATCH 2\n",
                "CASE 0 1\n",
                "REF 0\n",
                "CASE 1 1\n",
                "REF 1\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[5, 3], 3),
                i64_case(&[3, 5], 3),
                i64_case(&[7, 7], 7),
                i64_case(&[0, -1], -1),
            ],
            category: Category::MultiFunction,
        },
        // ex193: is_positive + abs
        ProgramSpec {
            id: "ex193_is_positive_abs",
            intent: "Define is_positive (returns Bool) and abs functions",
            assembly_template: concat!(
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "GT\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "FUNC 1 13\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "LT\n",
                "MATCH 2\n",
                "CASE 0 1\n",
                "REF 0\n",
                "CASE 1 2\n",
                "REF 0\n",
                "NEG\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[5], true),
                i64_to_bool_case(&[0], false),
                i64_to_bool_case(&[-3], false),
                i64_to_bool_case(&[1], true),
            ],
            category: Category::MultiFunction,
        },
        // ex194: square + cube
        ProgramSpec {
            id: "ex194_square_cube",
            intent: "Define square and cube functions",
            assembly_template: concat!(
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "REF 0\n",
                "MUL\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "FUNC 1 8\n",
                "PARAM I64\n",
                "REF 0\n",
                "REF 0\n",
                "MUL\n",
                "REF 0\n",
                "MUL\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[3], 9),
                i64_case(&[0], 0),
                i64_case(&[-2], 4),
                i64_case(&[1], 1),
            ],
            category: Category::MultiFunction,
        },
        // ex195: double + triple
        ProgramSpec {
            id: "ex195_double_triple",
            intent: "Define double and triple functions",
            assembly_template: concat!(
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "REF 0\n",
                "ADD\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "FUNC 1 8\n",
                "PARAM I64\n",
                "REF 0\n",
                "REF 0\n",
                "ADD\n",
                "REF 0\n",
                "ADD\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0004\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[4], 8),
                i64_case(&[0], 0),
                i64_case(&[-3], -6),
                i64_case(&[1], 2),
            ],
            category: Category::MultiFunction,
        },
        // ex196: mod + div
        ProgramSpec {
            id: "ex196_mod_div",
            intent: "Define modulo and divide functions",
            assembly_template: concat!(
                "FUNC 2 7\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "MOD\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "FUNC 2 7\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "DIV\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x000a\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[10, 3], 1),
                i64_case(&[7, 2], 1),
                i64_case(&[6, 3], 0),
                i64_case(&[17, 5], 2),
            ],
            category: Category::MultiFunction,
        },
        // ex197: sum + product
        ProgramSpec {
            id: "ex197_sum_product",
            intent: "Define sum and product functions",
            assembly_template: concat!(
                "FUNC 2 7\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "ADD\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "FUNC 2 7\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "MUL\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0004\n",
                "CONST I64 0x0000 0x0005\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[4, 5], 9),
                i64_case(&[0, 10], 10),
                i64_case(&[3, 3], 6),
                i64_case(&[-1, 1], 0),
            ],
            category: Category::MultiFunction,
        },
        // ex198: inc + square (entry calls inc)
        ProgramSpec {
            id: "ex198_chain_two",
            intent: "Define increment and square functions (entry calls increment)",
            assembly_template: concat!(
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "ADD\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "REF 0\n",
                "MUL\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[3], 4),
                i64_case(&[0], 1),
                i64_case(&[5], 6),
                i64_case(&[-1], 0),
            ],
            category: Category::MultiFunction,
        },
        // ex199: square + add_ten (entry calls square)
        ProgramSpec {
            id: "ex199_chain_reverse",
            intent: "Define square and add_ten functions (entry calls square)",
            assembly_template: concat!(
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "REF 0\n",
                "MUL\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "FUNC 1 6\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x000a\n",
                "ADD\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[3], 9),
                i64_case(&[0], 0),
                i64_case(&[4], 16),
                i64_case(&[-2], 4),
            ],
            category: Category::MultiFunction,
        },
    ]
}
