//! Recursive algorithms (20): ex145-ex164.

use super::{i64_case, i64_to_bool_case, Category, ProgramSpec};

pub fn programs() -> Vec<ProgramSpec> {
    vec![
        // ex145: factorial (n!)
        ProgramSpec {
            id: "ex145_factorial",
            intent: "Compute the factorial of n using recursion",
            assembly_template: concat!(
                "FUNC 1 17\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "LTE\n",
                "MATCH 2\n",
                "CASE 0 6\n",
                "REF 0\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "SUB\n",
                "RECURSE 100\n",
                "MUL\n",
                "CASE 1 1\n",
                "CONST I64 0x0000 0x0001\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[5], 120),
                i64_case(&[0], 1),
                i64_case(&[1], 1),
                i64_case(&[3], 6),
            ],
            category: Category::Recursive,
        },
        // ex146: fibonacci
        ProgramSpec {
            id: "ex146_fibonacci",
            intent: "Compute the nth Fibonacci number using recursion",
            assembly_template: concat!(
                "FUNC 1 20\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "LTE\n",
                "MATCH 2\n",
                "CASE 0 9\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "SUB\n",
                "RECURSE 100\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0002\n",
                "SUB\n",
                "RECURSE 100\n",
                "ADD\n",
                "CASE 1 1\n",
                "REF 0\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[0], 0),
                i64_case(&[1], 1),
                i64_case(&[5], 5),
                i64_case(&[7], 13),
            ],
            category: Category::Recursive,
        },
        // ex147: gcd (greatest common divisor)
        ProgramSpec {
            id: "ex147_gcd",
            intent: "Compute the greatest common divisor of two integers using Euclidean algorithm",
            assembly_template: concat!(
                "FUNC 2 17\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "EQ\n",
                "MATCH 2\n",
                "CASE 0 5\n",
                "REF 0\n",
                "REF 1\n",
                "REF 0\n",
                "MOD\n",
                "RECURSE 100\n",
                "CASE 1 1\n",
                "REF 1\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x000c\n",
                "CONST I64 0x0000 0x0008\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[12, 8], 4),
                i64_case(&[7, 3], 1),
                i64_case(&[100, 25], 25),
                i64_case(&[17, 17], 17),
            ],
            category: Category::Recursive,
        },
        // ex148: power (a^n)
        ProgramSpec {
            id: "ex148_power",
            intent: "Compute a to the power of n using recursion",
            assembly_template: concat!(
                "FUNC 2 19\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "LTE\n",
                "MATCH 2\n",
                "CASE 0 7\n",
                "REF 1\n",
                "REF 1\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "SUB\n",
                "RECURSE 100\n",
                "MUL\n",
                "CASE 1 1\n",
                "CONST I64 0x0000 0x0001\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0002\n",
                "CONST I64 0x0000 0x000a\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[2, 10], 1024),
                i64_case(&[3, 3], 27),
                i64_case(&[2, 0], 1),
                i64_case(&[5, 2], 25),
            ],
            category: Category::Recursive,
        },
        // ex149: sum_to_n (0+1+...+n)
        ProgramSpec {
            id: "ex149_sum_to_n",
            intent: "Compute the sum of integers from 0 to n using recursion",
            assembly_template: concat!(
                "FUNC 1 17\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "LTE\n",
                "MATCH 2\n",
                "CASE 0 6\n",
                "REF 0\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "SUB\n",
                "RECURSE 100\n",
                "ADD\n",
                "CASE 1 1\n",
                "CONST I64 0x0000 0x0000\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[5], 15),
                i64_case(&[0], 0),
                i64_case(&[1], 1),
                i64_case(&[10], 55),
            ],
            category: Category::Recursive,
        },
        // ex150: count_down
        ProgramSpec {
            id: "ex150_count_down",
            intent: "Count down from n to 0 using recursion",
            assembly_template: concat!(
                "FUNC 1 17\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "LTE\n",
                "MATCH 2\n",
                "CASE 0 6\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "SUB\n",
                "RECURSE 100\n",
                "CONST I64 0x0000 0x0001\n",
                "ADD\n",
                "CASE 1 1\n",
                "CONST I64 0x0000 0x0000\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[5], 5),
                i64_case(&[0], 0),
                i64_case(&[1], 1),
                i64_case(&[10], 10),
            ],
            category: Category::Recursive,
        },
        // ex151: multiply_recursive (a*b via repeated addition)
        ProgramSpec {
            id: "ex151_multiply_recursive",
            intent: "Multiply two integers using repeated addition via recursion",
            assembly_template: concat!(
                "FUNC 2 19\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "LTE\n",
                "MATCH 2\n",
                "CASE 0 7\n",
                "REF 1\n",
                "REF 1\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "SUB\n",
                "RECURSE 100\n",
                "ADD\n",
                "CASE 1 1\n",
                "CONST I64 0x0000 0x0000\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0003\n",
                "CONST I64 0x0000 0x0004\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[3, 4], 12),
                i64_case(&[5, 0], 0),
                i64_case(&[1, 1], 1),
                i64_case(&[7, 3], 21),
            ],
            category: Category::Recursive,
        },
        // ex152: is_even_recursive
        ProgramSpec {
            id: "ex152_is_even_recursive",
            intent: "Check if an integer is even using recursion",
            assembly_template: concat!(
                "FUNC 1 23\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "LTE\n",
                "MATCH 2\n",
                "CASE 0 12\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "EQ\n",
                "MATCH 2\n",
                "CASE 0 4\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0002\n",
                "SUB\n",
                "RECURSE 100\n",
                "CASE 1 1\n",
                "CONST BOOL 0x0000 0x0000\n",
                "EXHAUST\n",
                "CASE 1 1\n",
                "CONST BOOL 0x0001 0x0000\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0004\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_to_bool_case(&[0], true),
                i64_to_bool_case(&[1], false),
                i64_to_bool_case(&[4], true),
                i64_to_bool_case(&[7], false),
            ],
            category: Category::Recursive,
        },
        // ex153: integer_log2 (floor(log2(n)))
        ProgramSpec {
            id: "ex153_integer_log2",
            intent: "Compute the floor of log base 2 of n using recursion",
            assembly_template: concat!(
                "FUNC 1 17\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "LTE\n",
                "MATCH 2\n",
                "CASE 0 6\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0002\n",
                "DIV\n",
                "RECURSE 100\n",
                "CONST I64 0x0000 0x0001\n",
                "ADD\n",
                "CASE 1 1\n",
                "CONST I64 0x0000 0x0000\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0008\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[1], 0),
                i64_case(&[2], 1),
                i64_case(&[8], 3),
                i64_case(&[16], 4),
            ],
            category: Category::Recursive,
        },
        // ex154: half_round_up (ceil(n/2))
        ProgramSpec {
            id: "ex154_half_round_up",
            intent: "Compute ceil(n/2) using recursion by subtracting 2",
            assembly_template: concat!(
                "FUNC 1 17\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "LTE\n",
                "MATCH 2\n",
                "CASE 0 6\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0002\n",
                "SUB\n",
                "RECURSE 100\n",
                "CONST I64 0x0000 0x0001\n",
                "ADD\n",
                "CASE 1 1\n",
                "CONST I64 0x0000 0x0000\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0007\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[0], 0),
                i64_case(&[1], 1),
                i64_case(&[4], 2),
                i64_case(&[7], 4),
            ],
            category: Category::Recursive,
        },
        // ex155: subtract_to_zero (a-b via recursion)
        ProgramSpec {
            id: "ex155_subtract_to_zero",
            intent: "Compute a minus b using recursion",
            assembly_template: concat!(
                "FUNC 2 19\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "LTE\n",
                "MATCH 2\n",
                "CASE 0 7\n",
                "REF 1\n",
                "CONST I64 0x0000 0x0001\n",
                "SUB\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "SUB\n",
                "RECURSE 100\n",
                "CASE 1 1\n",
                "REF 1\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[5, 3], 2),
                i64_case(&[10, 0], 10),
                i64_case(&[7, 7], 0),
                i64_case(&[3, 1], 2),
            ],
            category: Category::Recursive,
        },
        // ex156: mod_recursive (a%b)
        ProgramSpec {
            id: "ex156_mod_recursive",
            intent: "Compute a modulo b using recursion",
            assembly_template: concat!(
                "FUNC 2 17\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "LT\n",
                "MATCH 2\n",
                "CASE 0 5\n",
                "REF 1\n",
                "REF 0\n",
                "SUB\n",
                "REF 0\n",
                "RECURSE 100\n",
                "CASE 1 1\n",
                "REF 1\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x000a\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[10, 3], 1),
                i64_case(&[7, 2], 1),
                i64_case(&[6, 3], 0),
                i64_case(&[1, 5], 1),
            ],
            category: Category::Recursive,
        },
        // ex157: div_recursive (a/b)
        ProgramSpec {
            id: "ex157_div_recursive",
            intent: "Compute integer division a/b using recursion",
            assembly_template: concat!(
                "FUNC 2 19\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 1\n",
                "REF 0\n",
                "LT\n",
                "MATCH 2\n",
                "CASE 0 7\n",
                "REF 1\n",
                "REF 0\n",
                "SUB\n",
                "REF 0\n",
                "RECURSE 100\n",
                "CONST I64 0x0000 0x0001\n",
                "ADD\n",
                "CASE 1 1\n",
                "CONST I64 0x0000 0x0000\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x000a\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[10, 3], 3),
                i64_case(&[7, 2], 3),
                i64_case(&[6, 3], 2),
                i64_case(&[1, 5], 0),
            ],
            category: Category::Recursive,
        },
        // ex158: sum_squares_recursive
        ProgramSpec {
            id: "ex158_sum_squares_recursive",
            intent: "Compute the sum of squares from 1 to n using recursion",
            assembly_template: concat!(
                "FUNC 1 19\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "LTE\n",
                "MATCH 2\n",
                "CASE 0 8\n",
                "REF 0\n",
                "REF 0\n",
                "MUL\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "SUB\n",
                "RECURSE 100\n",
                "ADD\n",
                "CASE 1 1\n",
                "CONST I64 0x0000 0x0000\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[1], 1),
                i64_case(&[3], 14),
                i64_case(&[0], 0),
                i64_case(&[4], 30),
            ],
            category: Category::Recursive,
        },
        // ex159: length_recursive (digit count)
        ProgramSpec {
            id: "ex159_length_recursive",
            intent: "Count the number of digits in a positive integer using recursion",
            assembly_template: concat!(
                "FUNC 1 17\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x000a\n",
                "LT\n",
                "MATCH 2\n",
                "CASE 0 6\n",
                "REF 0\n",
                "CONST I64 0x0000 0x000a\n",
                "DIV\n",
                "RECURSE 100\n",
                "CONST I64 0x0000 0x0001\n",
                "ADD\n",
                "CASE 1 1\n",
                "CONST I64 0x0000 0x0001\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x007b\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[0], 1),
                i64_case(&[5], 1),
                i64_case(&[42], 2),
                i64_case(&[999], 3),
            ],
            category: Category::Recursive,
        },
        // ex160: double_n_times
        ProgramSpec {
            id: "ex160_double_n_times",
            intent: "Double x a total of n times using recursion",
            assembly_template: concat!(
                "FUNC 2 19\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "LTE\n",
                "MATCH 2\n",
                "CASE 0 7\n",
                "REF 1\n",
                "REF 1\n",
                "ADD\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "SUB\n",
                "RECURSE 100\n",
                "CASE 1 1\n",
                "REF 1\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0001\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[1, 3], 8),
                i64_case(&[5, 0], 5),
                i64_case(&[3, 2], 12),
                i64_case(&[1, 4], 16),
            ],
            category: Category::Recursive,
        },
        // ex161: subtract_repeat
        ProgramSpec {
            id: "ex161_subtract_repeat",
            intent: "Subtract 1 from x a total of n times using recursion",
            assembly_template: concat!(
                "FUNC 2 19\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "LTE\n",
                "MATCH 2\n",
                "CASE 0 7\n",
                "REF 1\n",
                "CONST I64 0x0000 0x0001\n",
                "SUB\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "SUB\n",
                "RECURSE 100\n",
                "CASE 1 1\n",
                "REF 1\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x000a\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[10, 3], 7),
                i64_case(&[5, 5], 0),
                i64_case(&[0, 0], 0),
                i64_case(&[7, 2], 5),
            ],
            category: Category::Recursive,
        },
        // ex162: add_repeat
        ProgramSpec {
            id: "ex162_add_repeat",
            intent: "Add 1 to x a total of n times using recursion",
            assembly_template: concat!(
                "FUNC 2 19\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "LTE\n",
                "MATCH 2\n",
                "CASE 0 7\n",
                "REF 1\n",
                "CONST I64 0x0000 0x0001\n",
                "ADD\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "SUB\n",
                "RECURSE 100\n",
                "CASE 1 1\n",
                "REF 1\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x000a\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[10, 3], 13),
                i64_case(&[0, 5], 5),
                i64_case(&[1, 1], 2),
                i64_case(&[7, 0], 7),
            ],
            category: Category::Recursive,
        },
        // ex163: square_recursive
        ProgramSpec {
            id: "ex163_square_recursive",
            intent: "Compute the square of n using the identity n^2 = (n-1)^2 + 2n - 1",
            assembly_template: concat!(
                "FUNC 1 21\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "LTE\n",
                "MATCH 2\n",
                "CASE 0 10\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "SUB\n",
                "RECURSE 100\n",
                "REF 0\n",
                "ADD\n",
                "REF 0\n",
                "ADD\n",
                "CONST I64 0x0000 0x0001\n",
                "SUB\n",
                "CASE 1 1\n",
                "CONST I64 0x0000 0x0000\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0005\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[0], 0),
                i64_case(&[1], 1),
                i64_case(&[3], 9),
                i64_case(&[5], 25),
            ],
            category: Category::Recursive,
        },
        // ex164: repeated_square
        ProgramSpec {
            id: "ex164_repeated_square",
            intent: "Compute x raised to the power 2^n by repeated squaring",
            assembly_template: concat!(
                "FUNC 2 19\n",
                "PARAM I64\n",
                "PARAM I64\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0000\n",
                "LTE\n",
                "MATCH 2\n",
                "CASE 0 7\n",
                "REF 1\n",
                "REF 1\n",
                "MUL\n",
                "REF 0\n",
                "CONST I64 0x0000 0x0001\n",
                "SUB\n",
                "RECURSE 100\n",
                "CASE 1 1\n",
                "REF 1\n",
                "EXHAUST\n",
                "RET\n",
                "HASH 0x0000 0x0000 0x0000\n",
                "ENDFUNC\n",
                "CONST I64 0x0000 0x0002\n",
                "CONST I64 0x0000 0x0003\n",
                "CALL 0\n",
                "HALT\n",
            ),
            witness_cases: vec![
                i64_case(&[2, 0], 2),
                i64_case(&[2, 1], 4),
                i64_case(&[2, 2], 16),
                i64_case(&[2, 3], 256),
            ],
            category: Category::Recursive,
        },
    ]
}
